fixtures:
  repositories:
    stdlib: "https://github.com/puppetlabs/puppetlabs-stdlib.git"
    apt: "https://github.com/puppetlabs/puppetlabs-apt.git"
    mysql: "https://github.com/puppetlabs/puppetlabs-mysql.git"
  symlinks:
    mariadb: "#{source_dir}"
